**Computing the SVD**

In [3]:
import numpy as np
import numpy.linalg as la

In [4]:
np.random.seed(15)
n = 5
A = np.random.randn(n, n)

Now compute the eigenvalues and eigenvectors of ATA as eigvals and eigvecs using la.eig or la.eigh (symmetric):

In [5]:
eigvals, eigvecs = la.eigh(A.T.dot(A))

In [8]:


eigvals



array([ 0.08637178,  0.457892  ,  2.04177547,  2.34383161,  8.37000184])

Eigenvalues are real and positive. Coincidence?

In [7]:
eigvecs

array([[-0.42314866,  0.45307384,  0.38523275,  0.34286421, -0.59136213],
       [ 0.06927091, -0.54923835,  0.58840207, -0.46788522, -0.35833672],
       [ 0.10690407, -0.42673885, -0.58303925,  0.26551486, -0.62931118],
       [ 0.32181016,  0.54466815, -0.25369587, -0.64225211, -0.35060727],
       [ 0.83735088,  0.11954869,  0.31793453,  0.42490192, -0.0541074 ]])

Check that those are in fact eigenvectors and eigenvalues:

In [6]:
B = A.T.dot(A)
B - eigvecs.dot(np.diag(eigvals)).dot(la.inv(eigvecs))

array([[  0.00000000e+00,   1.33226763e-15,   0.00000000e+00,
         -2.22044605e-16,   1.33226763e-15],
       [  0.00000000e+00,  -2.22044605e-15,  -2.22044605e-15,
         -4.44089210e-16,   2.56739074e-16],
       [ -4.44089210e-16,  -8.88178420e-16,  -1.77635684e-15,
         -6.66133815e-16,   5.82867088e-16],
       [ -2.22044605e-16,  -2.22044605e-16,  -8.88178420e-16,
         -4.44089210e-16,   3.33066907e-16],
       [  0.00000000e+00,  -3.60822483e-16,  -8.32667268e-17,
          1.11022302e-16,   3.33066907e-16]])



eigvecs are orthonormal! (Why?)

Check:


In [7]:
eigvecs.T.dot(eigvecs) - np.eye(n)

array([[ 8.88178420e-16,  4.03771460e-16,  6.85129908e-18,
        -1.93447007e-16, -2.91627008e-16],
       [ 4.03771460e-16,  1.11022302e-15,  1.52478038e-16,
        -2.34536220e-16,  4.40813029e-16],
       [ 6.85129908e-18,  1.52478038e-16,  8.88178420e-16,
         8.31196341e-17,  1.06121530e-16],
       [-1.93447007e-16, -2.34536220e-16,  8.31196341e-17,
         4.44089210e-16,  1.18684501e-16],
       [-2.91627008e-16,  4.40813029e-16,  1.06121530e-16,
         1.18684501e-16,  4.44089210e-16]])

SVD

In [15]:
Sigma = np.diag(np.sqrt(eigvals))
Sigma

array([[0.29389076, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.67667718, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.42890709, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.53095774, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 2.89309555]])

In [16]:
V = eigvecs
V

array([[-0.42314866,  0.45307384,  0.38523275,  0.34286421, -0.59136213],
       [ 0.06927091, -0.54923835,  0.58840207, -0.46788522, -0.35833672],
       [ 0.10690407, -0.42673885, -0.58303925,  0.26551486, -0.62931118],
       [ 0.32181016,  0.54466815, -0.25369587, -0.64225211, -0.35060727],
       [ 0.83735088,  0.11954869,  0.31793453,  0.42490192, -0.0541074 ]])

In [0]:
U = A.dot(V).dot(la.inv(Sigma))
U

In [ ]:
# coding: utf-8 #
# Computing the SVD
# In[7]: import numpy as np import numpy.linalg as la 
# In[25]: np.random.seed(15) n = 5 A = np.random.randn(n, n) 
# Now compute the eigenvalues and eigenvectors of $A^TA$ as `eigvals` and `eigvecs` using `la.eig` or `la.eigh` (symmetric): 
# In[26]: eigvals, eigvecs = la.eigh(A.T.dot(A)) 
# In[27]: eigvals 
# Eigenvalues are real and positive. Coincidence?
# In[28]: eigvecs.shape 
# Check that those are in fact eigenvectors and eigenvalues:
# In[29]: B = A.T.dot(A) B - eigvecs.dot(np.diag(eigvals)).dot(la.inv(eigvecs)) 
# `eigvecs` are orthonormal! (Why?)
# 
# Check: 
# In[30]: eigvecs.T.dot(eigvecs) - np.eye(n) 
# ------ 
# Now piece together the SVD:
# In[19]: Sigma = np.diag(np.sqrt(eigvals))
# In[20]: V = eigvecs 
# In[38]: U = A.dot(V).dot(la.inv(Sigma))
# Check orthogonality of `U`: # In[39]: U.dot(U.T) - np.eye(n) 

In [12]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
print(U)
print("S",s)
print(VT)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# # populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# # select
# n_elements = 2
# Sigma = Sigma[:, :n_elements]
# VT = VT[:n_elements, :]
# # reconstruct
# print(U)
# print(Sigma)
# print(VT)
# B = U.dot(Sigma.dot(VT))
# print(B)
# # transform
# T = U.dot(Sigma)
# print(T)
# T = A.dot(VT.T)
# print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[-0.19101157  0.89266338  0.40824829]
 [-0.51371859  0.26348917 -0.81649658]
 [-0.8364256  -0.36568503  0.40824829]]
S [  9.69657342e+01   7.25578339e+00   5.82172067e-15]
[[-0.24139304 -0.25728686 -0.27318068 -0.2890745  -0.30496832 -0.32086214
  -0.33675595 -0.35264977 -0.36854359 -0.38443741]
 [-0.53589546 -0.42695236 -0.31800926 -0.20906617 -0.10012307  0.00882003
   0.11776313  0.22670623  0.33564933  0.44459242]
 [-0.76308471  0.57981078  0.1426451   0.09783039  0.10006951  0.08192046
  -0.02182071 -0.07111153  0.02343386 -0.16969316]
 [-0.11442628 -0.24159965 -0.22978376  0.9248098  -0.07469427 -0.07119775
  -0.05510443 -0.0470247  -0.06011372 -0.03086524]
 [-0.03428472 -0.13813055 -0.29451801 -0.06190924  0.92563949 -0.08203999
  -0.06968687 -0.07007771 -0.10413301 -0.07085938]
 [ 0.02720949 -0.03009057 -0.34021657 -0.04844604 -0.07353916  0.90753768
  -0.08548326 -0.09498217 -0

SVD for Pseudoinverse

The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular matrices where the number of rows and columns are not equal.

It is also called the the Moore-Penrose Inverse after two independent discoverers of the method or the Generalized Inverse.

    Matrix inversion is not defined for matrices that are not square. […] When A has more columns than rows, then solving a linear equation using the pseudoinverse provides one of the many possible solutions.

Check orthogonality of U:


In [11]:
U.dot(U.T) - np.eye(n)

array([[-1.11022302e-15, -7.67324533e-16, -6.67804308e-16,
         1.47963782e-15,  1.44717415e-16],
       [-7.67324533e-16,  6.66133815e-16, -5.43672425e-16,
         6.51481016e-16, -2.64998805e-16],
       [-6.67804308e-16, -5.43672425e-16,  2.66453526e-15,
        -1.42306617e-15,  1.55464267e-15],
       [ 1.47963782e-15,  6.51481016e-16, -1.42306617e-15,
         3.10862447e-15, -1.13201575e-15],
       [ 1.44717415e-16, -2.64998805e-16,  1.55464267e-15,
        -1.13201575e-15,  4.44089210e-16]])

np.eye gives Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [12]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [13]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

Using SVD function

In [14]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
